# Docker-compose configuration for development

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/database.Dockerfile
    ports:
      - 5432:5432

  db-test:
    build:
      context: .
      dockerfile: ./docker/database.Dockerfile
    ports:
      - 2345:5432

  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
      - db-test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8888:80
