export const COOKIE_API_TOKEN = 'API_TOKEN';

export const LOCAL_REQUEST_ID_KEY = 'REQUEST_ID';
export const LOCAL_SERVICE_LOCATOR_KEY = 'SERVICE_LOCATOR';
export const LOCAL_REQUESTING_USER_KEY = 'REQUESTING_USER';
