export const COOKIE_API_TOKEN = 'CARDGAME_API_TOKEN';

export const LOCAL_TRACE_ID_KEY = 'TRACE_ID';
export const LOCAL_SERVICE_LOCATOR_KEY = 'SERVICE_LOCATOR';
export const LOCAL_REQUESTING_USER_KEY = 'REQUESTING_USER';
