name: CI
on: [push]

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.17.0
      - name: Install dependencies
        run: yarn install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Run tests
        run: yarn test
        env:
          CI: true
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          file: packages/*/coverage/clover.xml
          fail_ci_if_error: true
