name: CI_CD
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  CI:
    name: Automated tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.5-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 2345:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  DEPLOYMENT-FRONTEND:
    name: Deployment - Frontend
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - run: yarn install
      - run: yarn wsrun -p @packages/frontend -r build
        env:
          REACT_APP_API_URI: 'https://benard-card-game-api.herokuapp.com'
      - uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: live-frontend
          FOLDER: packages/frontend/build
          CLEAN: true
