name: CI_CD
on: [push]

jobs:
  CI:
    name: Automated tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.5-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 2345:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Use Node v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install dependencies
        run: yarn install
      - name: Build all projects
        run: yarn build
      - name: Run automated tests
        run: yarn test
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  CD-FRONTEND:
    name: Deployment - Frontend
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install dependencies
        run: yarn install
      - name: Build frontend project
        run: yarn wsrun -p @packages/frontend -r build
        env:
          REACT_APP_API_URI: 'https://benard-card-game-api.herokuapp.com'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deployment-frontend
          FOLDER: packages/frontend/build
          CLEAN: true
